name: dlna-downloader
adopt-info: dlna-downloader
license: GPL-3.0
grade: stable

confinement: strict
base: core18

parts:
  dlna-downloader:
    plugin: dump
    source: .
    parse-info: [../../../project/com.moritzmolch.dlna-downloader.appdata.xml]
    #override-pull: ../../../project/null.sh
    #override-build: ../../../project/null.sh
    #override-stage: ../project/null.sh
    override-prime: ../project/override-prime.sh

apps:
  dlna-downloader:
    command: dlna-downloader
    desktop: ../project/com.moritzmolch.dlna-downloader.desktop
    extensions: [gnome-3-34]
    plugs:
      - desktop
      - home
      - removable-media
      - network
      - network-bind
      - wayland
    common-id: com.moritzmolch.dlna-downloader
