name: dlna-downloader
adopt-info: dlna-downloader
license: GPL-3.0
grade: stable
confinement: strict
base: core18
architectures:
  - build-on: amd64
#  - build-on: arm64
#  - build-on: armhf

parts:
  dlna-downloader:
    plugin: dump
    source: .
    parse-info: [dev/snap/com.moritzmolch.dlna-downloader.appdata.xml]
    override-prime: |
      ${SNAPCRAFT_PROJECT_DIR}/dev/snap/override-prime.sh

apps:
  dlna-downloader:
    command: dlna-downloader
    extensions: [gnome-3-34]
    plugs:
      - home
      - removable-media
      - network
      - network-bind
    common-id: com.moritzmolch.dlna-downloader
